/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROYECTO.ADMON.Producto;

import Clases.ClsCargaCombos;
import Clases.Sesion;
import ConexionMySql.ClsConexionMySql;
import Entidades.ClsProducto;

/**
 *
 * @author Freak
 */
public class FRMAlta extends javax.swing.JInternalFrame {

    /**
     * Creates new form FRMAlta
     */
    public FRMAlta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNumeroDeProducto = new javax.swing.JLabel();
        txtNumeroDeProducto = new javax.swing.JTextField();
        txtNombreDeProducto = new javax.swing.JTextField();
        txtCantidadDeMedida = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtCantidadAAlertar = new javax.swing.JTextField();
        lblCantidadAAlertar = new javax.swing.JLabel();
        lblCveAlertar = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblPrecioUnitario = new javax.swing.JLabel();
        lblCantidadDeMedida = new javax.swing.JLabel();
        lblCveUnidadDeMedida = new javax.swing.JLabel();
        lblNombreDeProducto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        cnbCveUnidadDeMedida = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        cnbCveAlertar = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(500, 620));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText(Glosario.Glosario.Producto.FRMAlta_getTitulo());

        lblNumeroDeProducto.setText(Glosario.Glosario.Producto.Producto_NumeroDeProducto());

        lblCantidadAAlertar.setText(Glosario.Glosario.Producto.Producto_CantidadAAlertar());

        lblCveAlertar.setText(Glosario.Glosario.Producto.Producto_CveAlertar());

        lblDescripcion.setText(Glosario.Glosario.Producto.Producto_Descripcion());

        lblPrecioUnitario.setText(Glosario.Glosario.Producto.Producto_PrecioUnitario());

        lblCantidadDeMedida.setText(Glosario.Glosario.Producto.Producto_CantidadDeMedida());

        lblCveUnidadDeMedida.setText(Glosario.Glosario.Producto.Producto_CveUnidadDeMedida());

        lblNombreDeProducto.setText(Glosario.Glosario.Producto.Producto_NombreDeProducto());

        txaDescripcion.setColumns(20);
        txaDescripcion.setLineWrap(true);
        txaDescripcion.setRows(5);
        jScrollPane2.setViewportView(txaDescripcion);

        cnbCveUnidadDeMedida.setModel(ClsCargaCombos.CargaComboPorClave("7","","--SELECCIONAR--",false));

        btnGuardar.setText(Glosario.Glosario.getGuardar());
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cnbCveAlertar.setModel(ClsCargaCombos.CargaComboPorClave("3","","--SELECCIONAR--",false));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroDeProducto)
                            .addComponent(lblNombreDeProducto)
                            .addComponent(lblCveUnidadDeMedida)
                            .addComponent(lblCantidadDeMedida)
                            .addComponent(lblPrecioUnitario)
                            .addComponent(lblDescripcion)
                            .addComponent(lblCveAlertar)
                            .addComponent(lblCantidadAAlertar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCantidadDeMedida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(txtCantidadAAlertar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroDeProducto)
                            .addComponent(txtNombreDeProducto)
                            .addComponent(cnbCveUnidadDeMedida, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cnbCveAlertar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroDeProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroDeProducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreDeProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreDeProducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCveUnidadDeMedida)
                    .addComponent(cnbCveUnidadDeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadDeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadDeMedida))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioUnitario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCveAlertar)
                    .addComponent(cnbCveAlertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadAAlertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadAAlertar))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        if (Sesion.CierreVentana(NumeroDePantalla)){
            this.dispose();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        long NumeroDeProducto = Long.parseLong(txtNumeroDeProducto.getText());
        String NombreDeProducto = txtNombreDeProducto.getText();
        ClsCargaCombos CveUnidadDeMedidaCnb = (ClsCargaCombos) cnbCveUnidadDeMedida.getSelectedItem();
        int CveUnidadDeMedida = CveUnidadDeMedidaCnb.SecuencialDeClave();
        String CantidadDeMedida = txtCantidadDeMedida.getText();
        double PrecioUnitario = Double.parseDouble(txtPrecioUnitario.getText());
        String Descripcion = txaDescripcion.getText();
        ClsCargaCombos CveAlertarCnb = (ClsCargaCombos) cnbCveAlertar.getSelectedItem();
        int CveAlertar = CveAlertarCnb.SecuencialDeClave();
        int CantidadAAlertar = Integer.parseInt(txtCantidadAAlertar.getText());
        ClsProducto Producto = new ClsProducto(NumeroDeProducto,NombreDeProducto,CveUnidadDeMedida,CantidadDeMedida,PrecioUnitario,Descripcion,CveAlertar,CantidadAAlertar,1);
        ClsConexionMySql.IniciaTrnsaccion();
        if (Producto.Insert()){
            ClsConexionMySql.Commit();
        }else{
            ClsConexionMySql.Rollback();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    public long NumeroDePantalla(){
        return NumeroDePantalla;
    }
    private long NumeroDePantalla = 17;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cnbCveAlertar;
    private javax.swing.JComboBox<String> cnbCveUnidadDeMedida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidadAAlertar;
    private javax.swing.JLabel lblCantidadDeMedida;
    private javax.swing.JLabel lblCveAlertar;
    private javax.swing.JLabel lblCveUnidadDeMedida;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombreDeProducto;
    private javax.swing.JLabel lblNumeroDeProducto;
    private javax.swing.JLabel lblPrecioUnitario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextField txtCantidadAAlertar;
    private javax.swing.JTextField txtCantidadDeMedida;
    private javax.swing.JTextField txtNombreDeProducto;
    private javax.swing.JTextField txtNumeroDeProducto;
    private javax.swing.JTextField txtPrecioUnitario;
    // End of variables declaration//GEN-END:variables
}
