/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROYECTO.ADMON.Correo;

import Clases.Sesion;
import Clases.ClsCargaCombos;
import Entidades.ClsCorreo;
import Funcionalidades.ClsOperaCorreo;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;

/**
 *
 * @author Freak
 */
public class FRMIndex extends javax.swing.JInternalFrame {

    /**
     * Creates new form FRMIndex
     */
    public FRMIndex() {
        initComponents();
    }
    private Object[][] CargaCorreosEnTabla() {
        String Filtro = "";
        List<ClsCorreo> lstCorreo = (new ClsOperaCorreo()).ConsultaLista("","", Filtro);
        Object Perfiles[][] = new Object[lstCorreo.size()][ClsCorreo.RelacionesCorreo.CamposQueSeMuestranEnTabla.size()];
        try{
        for (int x = 0; x < lstCorreo.size(); x++){
            for (int y = 0; y < ClsCorreo.RelacionesCorreo.CamposQueSeMuestranEnTabla.size(); y ++){
                Method getElemento = lstCorreo.get(x).getClass().getMethod(ClsCorreo.RelacionesCorreo.CamposQueSeMuestranEnTabla.get(y).Entidad());
                Perfiles[x][y] = getElemento.invoke(lstCorreo.get(x));
            }
        }
        }catch(IllegalAccessException | IllegalArgumentException | NoSuchMethodException | SecurityException | InvocationTargetException ex){
            System.out.println(ex.getMessage());
        }
        return Perfiles;
    }
    private String[] Titulos(){
        String Titulos[] = new String[ClsCorreo.RelacionesCorreo.CamposQueSeMuestranEnTabla.size()];
        for (int i = 0; i < ClsCorreo.RelacionesCorreo.CamposQueSeMuestranEnTabla.size(); i++){
            Titulos[i] = ClsCorreo.RelacionesCorreo.CamposQueSeMuestranEnTabla.get(i).Texto();
        }
        return Titulos;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCorreos = new javax.swing.JTable();
        btnAlta = new javax.swing.JButton();
        btnConfigurar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Correos");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(485, 436));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText(Glosario.Glosario.Correo.FRMIndex_getTitulo());

        tblCorreos.setModel(new javax.swing.table.DefaultTableModel(
            CargaCorreosEnTabla(),
            Titulos()
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false,false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCorreos.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblCorreos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCorreosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCorreos);

        btnAlta.setText(Glosario.Glosario.General_getAlta());
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnConfigurar.setText(Glosario.Glosario.General_getConfigurar());
        btnConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAlta)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfigurar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnConfigurar))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
        Class[] Tipos = new Class[0];
        Object[] Parametros = new Object[0];
        PROYECTO.DESKTOP.DesktopMain.AbrirPantalla("Correo.FRMAlta", Tipos, Parametros, false);
        if (Sesion.CierreVentana(NumeroDePantalla)){
            this.dispose();
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        if (Sesion.CierreVentana(NumeroDePantalla)){
            this.dispose();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void tblCorreosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCorreosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            int row = tblCorreos.rowAtPoint(evt.getPoint());
            Class[] Tipos = {ClsCorreo.class};
            ClsCorreo Correo = new ClsCorreo();
            Correo.NumeroDeCorreo(Long.parseLong(tblCorreos.getValueAt(row, 0).toString()));
            Correo.CveTipoDeCorreo(ClsCargaCombos.CambiaClave("5","",tblCorreos.getValueAt(row, 1).toString()));
            Correo.Correo(tblCorreos.getValueAt(row, 2).toString());
            Correo.CveEstatus(ClsCargaCombos.CambiaClave("1","",tblCorreos.getValueAt(row, 3).toString()));
            Correo.TextoTipoDeCorreo(tblCorreos.getValueAt(row, 1).toString());
            Correo.TextoEstatus(tblCorreos.getValueAt(row, 3).toString());
            Object[] Parametros = {Correo};
            PROYECTO.DESKTOP.DesktopMain.AbrirPantalla("Correo.FRMDetalle", Tipos, Parametros, false);
            if (Sesion.CierreVentana(NumeroDePantalla)){
                this.dispose();
            }
        }
    }//GEN-LAST:event_tblCorreosMouseClicked

    private void btnConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarActionPerformed
        // TODO add your handling code here:
        Class[] Tipos = new Class[0];
        Object[] Parametros = new Object[0];
        PROYECTO.DESKTOP.DesktopMain.AbrirPantalla("Correo.FRMConfigurar", Tipos, Parametros, false);
        if (Sesion.CierreVentana(NumeroDePantalla)){
            this.dispose();
        }
    }//GEN-LAST:event_btnConfigurarActionPerformed

    public long NumeroDePantalla(){
        return NumeroDePantalla;
    }
    private long NumeroDePantalla = 8;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnConfigurar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblCorreos;
    // End of variables declaration//GEN-END:variables
}
