/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROYECTO.LOGIN;

import Funcionalidades.ClsOperaUsuario;
import Clases.Sesion;
import PROYECTO.DESKTOP.DesktopMain;
import static PROYECTO.FuncionesParalelas.Contraseña.Desifrado;
import javax.swing.JOptionPane;

/**
 *
 * @author Freak
 */
public class FRMLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    // <editor-fold defaultstate="collapsed" desc="Constructor">
    public FRMLogin() {
        initComponents();
        Sesion.CveTipoDeMenu(1);
        Sesion.TextoTipoDeMenu("EMPLEADO");
        PROYECTO.FuncionesParalelas.Reloj reloj=new PROYECTO.FuncionesParalelas.Reloj(lblReloj);
        reloj.start();
    }// </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLoginTitle = new javax.swing.JLabel();
        jpnBordeNegro = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        pwdLogin = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblReloj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("FRMLogin"); // NOI18N

        txtLoginTitle.setFont(new java.awt.Font("Myriad CAD", 1, 24)); // NOI18N
        txtLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLoginTitle.setText(Glosario.Glosario.getLoginEmpleado());
        txtLoginTitle.setToolTipText("");
        txtLoginTitle.setAlignmentX(100.0F);
        txtLoginTitle.setAlignmentY(100.0F);

        jpnBordeNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsuario.setText(Glosario.Glosario.getLoginUsuario());

        lblContraseña.setText(Glosario.Glosario.getLoginContraseña());

        pwdLogin.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        pwdLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pwdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdLoginActionPerformed(evt);
            }
        });

        btnEntrar.setText(Glosario.Glosario.getEntrar());
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnRegistrar.setText(Glosario.Glosario.getRegistrar());
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("Hora");

        javax.swing.GroupLayout jpnBordeNegroLayout = new javax.swing.GroupLayout(jpnBordeNegro);
        jpnBordeNegro.setLayout(jpnBordeNegroLayout);
        jpnBordeNegroLayout.setHorizontalGroup(
            jpnBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBordeNegroLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jpnBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnBordeNegroLayout.createSequentialGroup()
                        .addGroup(jpnBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(87, 87, 87))
                    .addGroup(jpnBordeNegroLayout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jpnBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txtLogin)
                    .addComponent(pwdLogin))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBordeNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnBordeNegroLayout.setVerticalGroup(
            jpnBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBordeNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReloj)
                .addGap(23, 23, 23)
                .addGroup(jpnBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpnBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jpnBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpnBordeNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnBordeNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pwdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdLoginActionPerformed
        // TODO add your handling code here:
        if(!txtLogin.getText().equals("") && pwdLogin.getPassword().length != 0){
            String Usuario = txtLogin.getText().trim();
            String Contraseña = Desifrado(pwdLogin.getPassword());  
            if(txtLogin.getText().equals("Desarrollo") && Contraseña.equals("Des01.23")){
                Sesion.NumeroDeUsuario(0);
                Sesion.NombreDeUsuario(Usuario);
                this.dispose();
                DesktopMain Escritorio = new DesktopMain();
                Escritorio.setVisible(true);
            }else{
                Entidades.ClsUsuario Registro = (new ClsOperaUsuario()).Consulta("", Usuario, Contraseña);
                if(Registro.NumeroDeUsuario() != 0){
                    if (Usuario.equals(Registro.NombreDeUsuario()) && Contraseña.equals(Registro.ContraseñaDeUsuario())){
                        Sesion.NumeroDeUsuario(Registro.NumeroDeUsuario());
                        Sesion.NombreDeUsuario(Registro.NombreDeUsuario());
                        Sesion.RecuperaPerfil();
                        if (Sesion.TipoPermiso(Sesion.NumeroDePerfil(), NumeroDePantalla)){
                            this.dispose();
                            DesktopMain Escritorio = new DesktopMain();
                            Escritorio.setVisible(true);
                        }else{
                            JOptionPane.showMessageDialog(this, "El usuario " + Sesion.NombreDeUsuario() + " no cuenta con los permisos de acceso.", "Login", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Usuario no encontrado, Error de usuario o contraseña", "Login", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Usuario no encontrado, Error de usuario o contraseña", "Login", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Campos vacios", "Login", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_pwdLoginActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        if(!txtLogin.getText().equals("") && pwdLogin.getPassword().length != 0){
            String Usuario = txtLogin.getText().trim();
            String Contraseña = Desifrado(pwdLogin.getPassword());  
            if(txtLogin.getText().equals("Desarrollo") && Contraseña.equals("Des01.23")){
                Sesion.NumeroDeUsuario(0);
                Sesion.NombreDeUsuario(Usuario);
                this.dispose();
                DesktopMain Escritorio = new DesktopMain();
                Escritorio.setVisible(true);
            }else{
                Entidades.ClsUsuario Registro = (new ClsOperaUsuario()).Consulta("", Usuario, Contraseña);
                if(Registro.NumeroDeUsuario() != 0){
                    if (Usuario.equals(Registro.NombreDeUsuario()) && Contraseña.equals(Registro.ContraseñaDeUsuario())){
                        Sesion.NumeroDeUsuario(Registro.NumeroDeUsuario());
                        Sesion.NombreDeUsuario(Registro.NombreDeUsuario());
                        Sesion.RecuperaPerfil();
                        if (Sesion.TipoPermiso(Sesion.NumeroDePerfil(), NumeroDePantalla)){
                            this.dispose();
                            DesktopMain Escritorio = new DesktopMain();
                            Escritorio.setVisible(true);
                        }else{
                            JOptionPane.showMessageDialog(this, "El usuario " + Sesion.NombreDeUsuario() + " no cuenta con los permisos de acceso.", "Login", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Usuario no encontrado, Error de usuario o contraseña", "Login", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Usuario no encontrado, Error de usuario o contraseña", "Login", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Campos vacios", "Login", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FRMRegistrar frmRegistrar=new FRMRegistrar();
        frmRegistrar.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMLogin().setVisible(true);
            }
        });
    }

    public long NumeroDePantalla(){
        return NumeroDePantalla;
    }
    private long NumeroDePantalla = 0;
    public static PROYECTO.FuncionesParalelas.Reloj horaES;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jpnBordeNegro;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pwdLogin;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JLabel txtLoginTitle;
    // End of variables declaration//GEN-END:variables
}
